name: intl_message
description: Parses and formats ICU Message strings.
version: 0.1.4+3
homepage: https://github.com/appsup-dart/intl_message
author: Rik Bellens <rik.bellens@appsup.be>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  intl: '>=0.15.2 <0.17.0'
  petitparser: ">=1.7.6 <3.0.0"

dev_dependencies:
  test: ">=0.12.0 <2.0.0"
