name: intl_message
description: Parses and formats ICU Message strings. Formats strings in multiple languages.
version: 0.2.0+1
homepage: https://github.com/appsup-dart/intl_message
author: Rik Bellens <rik.bellens@appsup.be>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  intl: '>=0.15.2 <0.17.0'
  petitparser: ">=1.7.6 <4.0.0"
  expressions: ^0.1.4

dev_dependencies:
  test: ">=0.12.0 <2.0.0"
  pedantic: ^1.9.0
